name = "openai-cf"# todo
main = "index.js"
compatibility_date = "2024-11-11"

[ai]
binding = "AI" # i.e. available in your Worker on env.AI

[[r2_buckets]]
binding = "IMAGE_BUCKET"
bucket_name = "openai-cf-images"
preview_bucket_name = "ai-images"

[vars]
CLOUDFLARE_ACCOUNT_ID = "09fcd959d3815207e18adf9620beac72" # replace with your own.
MODEL_MAPPER = { "gpt-4o-mini" = "@cf/meta/llama-3.3-70b-instruct-fp8-fast" } # Optional

[observability.logs]
enabled = true
# head_sampling_rate = 1 # optional. default = 1.
invocation_logs = true

[placement]
mode = "smart"